# Generated by Django 3.2.4 on 2021-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0002_auto_20210726_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(max_length=50),
        ),
    ]
