# Generated by Django 3.2.5 on 2021-08-18 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0005_auto_20210818_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_desc',
            field=models.CharField(max_length=1000),
            preserve_default=False,
        ),
    ]
