# Generated by Django 3.2.5 on 2021-08-23 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0014_quoterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='vendor_id',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
    ]
