# Generated by Django 3.2.5 on 2021-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0015_alter_quoterequest_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vendor_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
