# Generated by Django 3.2.5 on 2021-08-21 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chattwpn', '0003_auto_20210821_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(max_length=1000),
            preserve_default=False,
        ),
    ]
