# Generated by Django 3.2.5 on 2021-08-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattwpn', '0004_user_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='values',
        ),
    ]
