# Generated by Django 3.2.5 on 2021-08-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattwpn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
