# Generated by Django 3.2.5 on 2021-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattwpn', '0002_rename_content_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='number',
        ),
    ]
