# Generated by Django 3.2.4 on 2021-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_address', models.CharField(max_length=50)),
                ('vendor_contact', models.BigIntegerField()),
            ],
        ),
    ]
