# Generated by Django 3.2.4 on 2021-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(default='abc@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(max_length=100),
        ),
    ]
