# Generated by Django 3.2.5 on 2021-08-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0006_vendor_vendor_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_desc',
            field=models.CharField(max_length=150),
        ),
    ]
