# Generated by Django 3.2.5 on 2021-08-20 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0007_auto_20210819_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_district',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur')], default='Kathmandu', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
