# Generated by Django 3.2.5 on 2021-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0009_images_review_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
