# Generated by Django 3.2.5 on 2021-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0011_contact_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=50)),
                ('weburl', models.URLField()),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.BigIntegerField()),
                ('district', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
    ]
