# Generated by Django 3.2.5 on 2021-08-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0013_membershipform_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.BigIntegerField()),
                ('msg', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twpn.vendor')),
            ],
        ),
    ]
