# Generated by Django 3.2.5 on 2021-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpn', '0016_alter_review_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='review',
            name='vendor_name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
