# Generated by Django 3.2.5 on 2021-08-25 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twpn', '0017_auto_20210823_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
